package trabalho.view;

import java.awt.Panel;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import org.knowm.xchart.*;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import trabalho.dao.NearEarthObjectDao;
import trabalho.model.NearEarthObject;
import trabalho.dao.NeoApi;
import trabalho.model.NeoFeed;
//import trabalho.dto.NeoObject;;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author lucas.wojahn
 */
public class TelaInicialView extends javax.swing.JFrame {

    private volatile boolean running = true;
    private final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    private final NearEarthObjectDao daoObjects = new NearEarthObjectDao();

    /**
     * Creates new form Dashboard
     */
    public TelaInicialView() {
        initComponents();
        loadDataFromDB();
        new Thread(this::updateLabel).start();

    }

    private void updateLabel() {
        while (running) {
            SwingUtilities.invokeLater(() -> timeCounter.setText(dtf.format(LocalDateTime.now())));
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                System.out.println("Erro ao atualizar data");
                System.out.println(e);
                running = false;
            }
        }
    }

    private void loadDataFromDB() {

        try {
            List<NearEarthObject> objects = this.daoObjects.findAll();

            this.mountTableWithData(objects);

        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao conectar no banco de dados", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void mountTableWithData(List<NearEarthObject> objects) {
        DefaultTableModel tableModel = new DefaultTableModel();
        jTableNearObjects.setModel(tableModel);

        tableModel.addColumn("ID");
        tableModel.addColumn("Nome");
        tableModel.addColumn("Distância");
        tableModel.addColumn("Tamanho Min (KM)");
        tableModel.addColumn("Tamanho Max (KM)");
        tableModel.addColumn("Velocidade (Km/h)");
        tableModel.addColumn("Velocidade (Km/s)");
        tableModel.addColumn("Risco");

        detectedObjects.setText(String.valueOf(objects.size()));

        for (int x = 0; x < objects.size(); x++) {
            tableModel.insertRow(x, new Object[]{objects.get(x).getId(),
                objects.get(x).getName(),
                objects.get(x).getAproachData().get(0).getMissDistance().getKilometers(),
                objects.get(x).getDiameter().getKilometer().getMin(),
                objects.get(x).getDiameter().getKilometer().getMax(),
                objects.get(x).getAproachData().get(0).getVelocity().getKmH(),
                objects.get(x).getAproachData().get(0).getVelocity().getKmS(),
                objects.get(x).isIsPotentiallyHazardousAsteroid(),});
        }
    }

    private void loadDataFromDBOrdered(List<String> campos, String mode) {

        try {
            List<NearEarthObject> objects = this.daoObjects.findOrderBy(campos, mode);
            this.mountTableWithData(objects);

        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao conectar no banco e ordenar dados", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelDash = new javax.swing.JPanel();
        timeCounter = new javax.swing.JLabel();
        detectedObjects = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNearObjects = new javax.swing.JTable();
        jButtonAttData = new javax.swing.JButton();
        checkBoxDistancia = new java.awt.Checkbox();
        checkBoxSize = new java.awt.Checkbox();
        checkBoxVelocity = new java.awt.Checkbox();
        checkBoxHazard = new java.awt.Checkbox();
        jButtonFilter = new javax.swing.JButton();
        jComboBoxMode = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonGraph = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuConfiguracoes = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDash.setBorder(javax.swing.BorderFactory.createTitledBorder("Dashboard"));

        timeCounter.setText("jLabel1");

        detectedObjects.setText("jLabel1");

        label1.setText("Timer:");

        label2.setText("Objetos Detectados:");

        jTableNearObjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Distancia"
            }
        ));
        jScrollPane1.setViewportView(jTableNearObjects);

        jButtonAttData.setText("Atualizar Dados");
        jButtonAttData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttDataActionPerformed(evt);
            }
        });

        checkBoxDistancia.setLabel("Distância");

        checkBoxSize.setLabel("Tamanho");

        checkBoxVelocity.setLabel("Velocidade");

        checkBoxHazard.setLabel("Risco");

        jButtonFilter.setLabel("Filtrar");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jComboBoxMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASC", "DESC" }));
        jComboBoxMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModeActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Buscar");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTextFieldSearch.setText("ID ou Nome");
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        jButtonGraph.setText("Gerar Gráfico");
        jButtonGraph.setActionCommand("");
        jButtonGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDashLayout = new javax.swing.GroupLayout(jPanelDash);
        jPanelDash.setLayout(jPanelDashLayout);
        jPanelDashLayout.setHorizontalGroup(
            jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelDashLayout.createSequentialGroup()
                        .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDashLayout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeCounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelDashLayout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detectedObjects)))
                        .addGap(74, 74, 74)
                        .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDashLayout.createSequentialGroup()
                                .addComponent(jButtonAttData, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDashLayout.createSequentialGroup()
                                .addComponent(jButtonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(checkBoxDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkBoxHazard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jComboBoxMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanelDashLayout.setVerticalGroup(
            jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAttData)
                    .addComponent(jButtonGraph)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDashLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detectedObjects)))
                    .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonFilter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSearch)
                            .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(checkBoxDistancia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBoxSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBoxVelocity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBoxHazard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        timeCounter.getAccessibleContext().setAccessibleName("TimeCounter");
        label1.getAccessibleContext().setAccessibleName("Timer");
        label2.getAccessibleContext().setAccessibleName("objDetectedLabel");
        jButtonAttData.getAccessibleContext().setAccessibleName("jButtonAttData");
        jButtonFilter.getAccessibleContext().setAccessibleName("jButtonFilter");

        jMenu1.setText("Arquivo");

        jMenuItem2.setText("Dashboard");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDashboard(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Sair");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dados");

        jMenuItem4.setText("Atualizar Dados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAtualizarDadosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Resultados");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenuConfiguracoes.setText("Configurações");
        jMenuConfiguracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuConfiguracoesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuConfiguracoes);

        jMenu5.setText("Ajuda");

        jMenuItemAbout.setText("Sobre");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemAbout);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanelDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanelDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDashboard(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDashboard

    }//GEN-LAST:event_jMenuItemDashboard

    private void jMenuItemAtualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAtualizarDadosActionPerformed

    }//GEN-LAST:event_jMenuItemAtualizarDadosActionPerformed

    private void jButtonAttDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttDataActionPerformed
        NeoApi api = new NeoApi();
        NeoFeed data;

        try {
            String currentDate = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            System.out.println(currentDate);

            String limitDateApi = LocalDate.now().minusDays(7).format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            System.out.println(currentDate);
            System.out.println(limitDateApi);
            //Limite de data da API parece ser 7 Dias senão da erro
            data = api.buscarDados(limitDateApi, currentDate);
            System.out.println(data.toString());
            System.out.println("Objetos detectados: " + data.getCount());
            detectedObjects.setText(String.valueOf(data.getCount()));

            Map<String, List<NearEarthObject>> map = data.getNearEarthObjects();

            for (String currDate : map.keySet()) {
                List<NearEarthObject> objects = data.getNearEarthObjects().get(currDate);
                try {
                    daoObjects.saveList(objects);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaInicialView.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, "Erro ao conectar no banco de dados", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }

            this.loadDataFromDB();

        } catch (IOException ex) {
            Logger.getLogger(TelaInicialView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao tentar obter informações da NASA", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAttDataActionPerformed

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        List<String> campos = new ArrayList();

        if (checkBoxDistancia.getState()) {
            System.out.println("distancia enabled");
            campos.add("kilometers");
        }
        if (checkBoxHazard.getState()) {
            System.out.println("risco enabled");
            campos.add("is_potentially_hazardous_asteroid");

        }
        if (checkBoxSize.getState()) {
            System.out.println("tamanho enabled");
            campos.add("max_diameter");

        }
        if (checkBoxVelocity.getState()) {
            System.out.println("velocidade enabled");
            campos.add("kilometers_second");

        }

        String mode = (String) jComboBoxMode.getSelectedItem();

        this.loadDataFromDBOrdered(campos, mode);
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jComboBoxModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxModeActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        SobreView aboutFrame = new SobreView();
        aboutFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

        try {
            String searchText = jTextFieldSearch.getText();
            if (searchText.isBlank()) {
                this.loadDataFromDB();
            } else {
                List<NearEarthObject> objects = daoObjects.findSearch(searchText);
                this.mountTableWithData(objects);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButtonGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraphActionPerformed
        NeoApi api = new NeoApi();
        NeoFeed data;

        try {
            String currentDate = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            System.out.println(currentDate);

            String limitDateApi = LocalDate.now().minusDays(7).format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            System.out.println(currentDate);
            System.out.println(limitDateApi);

            data = api.buscarDados(limitDateApi, currentDate);
            detectedObjects.setText(String.valueOf(data.getCount()));

            Map<String, List<NearEarthObject>> map = data.getNearEarthObjects();

            CategoryChart chart = new CategoryChartBuilder().width(1000).height(800).title("Objetos encontrados por dia").xAxisTitle("Dia").yAxisTitle("Quantidade").build();

            List<String> xData = new ArrayList<>(map.keySet());
            List<Integer> yData = new ArrayList<>();
            
            for (String key : map.keySet()) {
                yData.add(map.get(key).size());
            }

            chart.addSeries("Quantidade Objetos", xData, yData);

            XChartPanel<CategoryChart> chartPanel = new XChartPanel<>(chart);
            JFrame frame = new JFrame("Gráfico");
            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            frame.add(chartPanel);
            frame.pack();
            frame.setVisible(true);

        } catch (IOException ex) {
            Logger.getLogger(TelaInicialView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGraphActionPerformed

    private void jMenuConfiguracoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConfiguracoesMouseClicked
        ConfiguracoesView configFrame = new ConfiguracoesView();
        configFrame.setVisible(true);
    }//GEN-LAST:event_jMenuConfiguracoesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkBoxDistancia;
    private java.awt.Checkbox checkBoxHazard;
    private java.awt.Checkbox checkBoxSize;
    private java.awt.Checkbox checkBoxVelocity;
    private javax.swing.JLabel detectedObjects;
    private javax.swing.JButton jButtonAttData;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonGraph;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBoxMode;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfiguracoes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JPanel jPanelDash;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNearObjects;
    private javax.swing.JTextField jTextFieldSearch;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel timeCounter;
    // End of variables declaration//GEN-END:variables
}
